import { l, type Artwork, type L10n, type QuizQuestion } from "./types";

const Q = (id: string, question: L10n, correct: L10n, w1: L10n, w2: L10n, w3: L10n, explain: L10n): QuizQuestion => ({
  id,
  question,
  options: [correct, w1, w2, w3],
  explain,
});

const LOUVRE = l("Musée du Louvre, Paris", "Bảo tàng Louvre, Paris");
const UFFIZI = l("Uffizi Gallery, Florence", "Phòng tranh Uffizi, Florence");
const NG_LONDON = l("National Gallery, London", "Phòng tranh Quốc gia, London");
const KHM = l("Kunsthistorisches Museum, Vienna", "Bảo tàng Lịch sử Nghệ thuật, Vienna");

export const ARTWORKS: Artwork[] = [
  {
    id: "mona-lisa",
    title: l("Mona Lisa", "Mona Lisa"),
    artist: "Leonardo da Vinci",
    year: "c. 1503–1519",
    museum: LOUVRE,
    aspect: "3:4",
    commons: "Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg",
    difficulty: "medium",
    funFact: l(
      "The painting was stolen from the Louvre in 1911 and only recovered two years later in Florence.",
      "Bức tranh từng bị đánh cắp khỏi Louvre năm 1911 và hai năm sau mới được tìm lại ở Florence.",
    ),
    quiz: [
      Q("mona-museum", l("Where is the Mona Lisa displayed today?", "Ngày nay Mona Lisa được trưng bày ở đâu?"),
        l("The Louvre, Paris", "Bảo tàng Louvre, Paris"), l("The Uffizi, Florence", "Uffizi, Florence"),
        l("The Prado, Madrid", "Prado, Madrid"), l("The National Gallery, London", "Phòng tranh Quốc gia, London"),
        l("It has been in the French royal collection since the 16th century and in the Louvre since the Revolution.", "Tranh thuộc bộ sưu tập hoàng gia Pháp từ thế kỷ 16 và ở Louvre từ sau Cách mạng Pháp.")),
      Q("mona-support", l("What is the Mona Lisa painted on?", "Mona Lisa được vẽ trên chất liệu gì?"),
        l("A poplar wood panel", "Tấm gỗ dương"), l("Canvas", "Vải canvas"), l("A copper sheet", "Tấm đồng"), l("A plaster wall", "Tường vữa"),
        l("Leonardo used oil paint on a single plank of poplar.", "Leonardo vẽ sơn dầu trên một tấm gỗ dương nguyên khối.")),
      Q("mona-sitter", l("Who is traditionally identified as the sitter?", "Người mẫu trong tranh theo truyền thống được cho là ai?"),
        l("Lisa Gherardini", "Lisa Gherardini"), l("Isabella d'Este", "Isabella d'Este"), l("Cecilia Gallerani", "Cecilia Gallerani"), l("Ginevra de' Benci", "Ginevra de' Benci"),
        l("Lisa Gherardini was the wife of the Florentine silk merchant Francesco del Giocondo — hence the name 'La Gioconda'.", "Lisa Gherardini là vợ thương nhân tơ lụa Francesco del Giocondo ở Florence — vì thế tranh còn có tên 'La Gioconda'.")),
      Q("mona-stolen", l("In which year was the Mona Lisa stolen from the Louvre?", "Mona Lisa bị đánh cắp khỏi Louvre năm nào?"),
        l("1911", "1911"), l("1871", "1871"), l("1938", "1938"), l("1962", "1962"),
        l("Vincenzo Peruggia, who had worked at the museum, hid it in his flat for two years.", "Vincenzo Peruggia, người từng làm việc ở bảo tàng, giấu tranh trong căn hộ suốt hai năm.")),
      Q("mona-sfumato", l("What is the name of Leonardo's soft, smoky blending of tones?", "Kỹ thuật chuyển sắc mờ như khói của Leonardo gọi là gì?"),
        l("Sfumato", "Sfumato"), l("Pointillism", "Chấm điểm (pointillism)"), l("Impasto", "Impasto"), l("Grisaille", "Grisaille"),
        l("Sfumato comes from the Italian word for smoke; it gives the face its famous soft edges.", "Sfumato bắt nguồn từ chữ 'khói' trong tiếng Ý; nó tạo nên những đường viền mềm nổi tiếng trên khuôn mặt.")),
    ],
  },
  {
    id: "last-supper",
    title: l("The Last Supper", "Bữa tiệc ly"),
    artist: "Leonardo da Vinci",
    year: "1495–1498",
    museum: l("Santa Maria delle Grazie, Milan", "Tu viện Santa Maria delle Grazie, Milan"),
    aspect: "16:9",
    commons: "Leonardo_da_Vinci_(1452-1519)_-_The_Last_Supper_(1495-1498).jpg",
    difficulty: "hard",
    funFact: l(
      "Leonardo painted on dry plaster instead of using true fresco, so the paint began flaking within his lifetime.",
      "Leonardo vẽ lên vữa khô thay vì kỹ thuật bích hoạ ướt truyền thống, nên sơn bắt đầu bong tróc ngay khi ông còn sống.",
    ),
    quiz: [
      Q("supper-city", l("In which city is The Last Supper?", "Bữa tiệc ly nằm ở thành phố nào?"),
        l("Milan", "Milan"), l("Florence", "Florence"), l("Rome", "Rome"), l("Venice", "Venice"),
        l("It is on a wall of the convent of Santa Maria delle Grazie.", "Tranh nằm trên tường tu viện Santa Maria delle Grazie.")),
      Q("supper-room", l("What room was it painted for?", "Bức tranh được vẽ cho căn phòng nào?"),
        l("The monks' dining hall (refectory)", "Nhà ăn của tu sĩ"), l("A chapel ceiling", "Trần một nhà nguyện"),
        l("A palace ballroom", "Phòng khiêu vũ trong cung điện"), l("A library", "Một thư viện"),
        l("The monks ate their meals beneath Christ's final meal.", "Các tu sĩ dùng bữa ngay bên dưới bữa ăn cuối cùng của Chúa.")),
      Q("supper-moment", l("Which moment does the painting show?", "Bức tranh khắc hoạ khoảnh khắc nào?"),
        l("Jesus announcing that one of the apostles will betray him", "Chúa Giêsu báo rằng một tông đồ sẽ phản bội Người"),
        l("The resurrection", "Sự phục sinh"), l("The wedding at Cana", "Tiệc cưới Cana"), l("The baptism of Jesus", "Lễ rửa tội của Chúa"),
        l("The apostles react in groups of three to the shocking announcement.", "Các tông đồ phản ứng theo từng nhóm ba người trước lời tuyên bố gây sốc.")),
      Q("supper-figures", l("How many people sit at the table?", "Có bao nhiêu người ngồi ở bàn?"),
        l("13", "13"), l("12", "12"), l("10", "10"), l("15", "15"),
        l("Jesus and his twelve apostles.", "Chúa Giêsu và mười hai tông đồ.")),
      Q("supper-technique", l("Why has the painting deteriorated so badly?", "Vì sao bức tranh xuống cấp nghiêm trọng?"),
        l("It was painted on dry plaster, not true fresco", "Vẽ trên vữa khô, không phải bích hoạ ướt"),
        l("It was painted with watercolour", "Vẽ bằng màu nước"), l("It was kept outdoors", "Bị để ngoài trời"), l("It was cut into pieces", "Bị cắt thành nhiều mảnh"),
        l("Tempera and oil on dry plaster let Leonardo work slowly, but the paint never bonded to the wall.", "Tempera và dầu trên vữa khô cho phép Leonardo vẽ chậm, nhưng sơn không bám chặt vào tường.")),
    ],
  },
  {
    id: "lady-with-an-ermine",
    title: l("Lady with an Ermine", "Người đàn bà bế chồn"),
    artist: "Leonardo da Vinci",
    year: "c. 1489–1491",
    museum: l("Czartoryski Museum, Kraków", "Bảo tàng Czartoryski, Kraków"),
    aspect: "3:4",
    commons: "Lady_with_an_Ermine_-_Leonardo_da_Vinci_-_Google_Art_Project.jpg",
    difficulty: "easy",
    funFact: l(
      "It is one of only four surviving portraits of women by Leonardo.",
      "Đây là một trong bốn bức chân dung phụ nữ còn lại của Leonardo.",
    ),
    quiz: [
      Q("ermine-animal", l("What animal is the woman holding?", "Người phụ nữ đang bế con vật gì?"),
        l("An ermine (stoat)", "Một con chồn ecmin"), l("A cat", "Một con mèo"), l("A small dog", "Một chú chó nhỏ"), l("A rabbit", "Một con thỏ"),
        l("The ermine was a symbol of purity and an emblem linked to Ludovico Sforza.", "Chồn ecmin tượng trưng cho sự trong sạch và gắn với Ludovico Sforza.")),
      Q("ermine-sitter", l("Who is the sitter?", "Người mẫu là ai?"),
        l("Cecilia Gallerani", "Cecilia Gallerani"), l("Lisa Gherardini", "Lisa Gherardini"), l("Beatrice d'Este", "Beatrice d'Este"), l("Lucrezia Borgia", "Lucrezia Borgia"),
        l("Cecilia Gallerani was a young woman at the Milanese court of Ludovico Sforza.", "Cecilia Gallerani là một thiếu nữ ở triều đình Milan của Ludovico Sforza.")),
      Q("ermine-city", l("In which city is the painting kept?", "Bức tranh được lưu giữ ở thành phố nào?"),
        l("Kraków", "Kraków"), l("Milan", "Milan"), l("Vienna", "Vienna"), l("Paris", "Paris"),
        l("It belongs to the Czartoryski collection, part of the National Museum in Kraków.", "Tranh thuộc bộ sưu tập Czartoryski, một phần của Bảo tàng Quốc gia Kraków.")),
      Q("ermine-court", l("Leonardo painted it while working for which ruler?", "Leonardo vẽ tranh khi phục vụ nhà cầm quyền nào?"),
        l("Ludovico Sforza of Milan", "Ludovico Sforza xứ Milan"), l("Lorenzo de' Medici", "Lorenzo de' Medici"),
        l("King Francis I of France", "Vua Francis I của Pháp"), l("Pope Julius II", "Giáo hoàng Julius II"),
        l("Leonardo spent almost twenty years at the Sforza court in Milan.", "Leonardo làm việc gần hai mươi năm ở triều đình Sforza tại Milan.")),
      Q("ermine-count", l("How many portraits of women by Leonardo survive?", "Có bao nhiêu chân dung phụ nữ của Leonardo còn tồn tại?"),
        l("Four", "Bốn"), l("One", "Một"), l("Twelve", "Mười hai"), l("Twenty", "Hai mươi"),
        l("Mona Lisa, Ginevra de' Benci, La Belle Ferronnière and this one.", "Mona Lisa, Ginevra de' Benci, La Belle Ferronnière và bức này.")),
    ],
  },
  {
    id: "ginevra-de-benci",
    title: l("Ginevra de' Benci", "Ginevra de' Benci"),
    artist: "Leonardo da Vinci",
    year: "c. 1474–1478",
    museum: l("National Gallery of Art, Washington", "Phòng tranh Quốc gia, Washington"),
    aspect: "1:1",
    commons: "Leonardo_da_Vinci_-_Ginevra_de'_Benci_-_Google_Art_Project.jpg",
    difficulty: "easy",
    funFact: l(
      "It is the only painting by Leonardo on public display in the Americas.",
      "Đây là bức tranh duy nhất của Leonardo được trưng bày công khai ở châu Mỹ.",
    ),
    quiz: [
      Q("ginevra-plant", l("Which shrub frames her head — a pun on her name?", "Bụi cây nào bao quanh đầu cô — một cách chơi chữ với tên cô?"),
        l("Juniper", "Cây bách xù (juniper)"), l("Olive", "Cây ô liu"), l("Laurel", "Cây nguyệt quế"), l("Rose", "Hoa hồng"),
        l("Juniper is 'ginepro' in Italian, echoing 'Ginevra'.", "Bách xù trong tiếng Ý là 'ginepro', gần với tên 'Ginevra'.")),
      Q("ginevra-museum", l("Where is the portrait today?", "Ngày nay bức chân dung ở đâu?"),
        l("National Gallery of Art, Washington", "Phòng tranh Quốc gia, Washington"), l("The Louvre, Paris", "Louvre, Paris"),
        l("The Uffizi, Florence", "Uffizi, Florence"), l("The Hermitage, St Petersburg", "Hermitage, St Petersburg"),
        l("The museum bought it in 1967 from the Princes of Liechtenstein.", "Bảo tàng mua tranh năm 1967 từ các hoàng thân Liechtenstein.")),
      Q("ginevra-city", l("Which city was Ginevra from?", "Ginevra là người thành phố nào?"),
        l("Florence", "Florence"), l("Venice", "Venice"), l("Naples", "Naples"), l("Genoa", "Genoa"),
        l("She was a member of a wealthy Florentine banking family.", "Cô thuộc một gia đình ngân hàng giàu có ở Florence.")),
      Q("ginevra-back", l("What is painted on the back of the panel?", "Mặt sau tấm gỗ được vẽ gì?"),
        l("A juniper sprig in a wreath with a Latin motto", "Cành bách xù trong vòng hoa kèm khẩu hiệu Latin"),
        l("Leonardo's self-portrait", "Chân dung tự hoạ của Leonardo"), l("A map of Florence", "Bản đồ Florence"), l("Nothing", "Không có gì"),
        l("The motto reads 'Virtutem forma decorat' — beauty adorns virtue.", "Khẩu hiệu là 'Virtutem forma decorat' — vẻ đẹp tô điểm cho đức hạnh.")),
      Q("ginevra-cut", l("Why do we not see her hands?", "Vì sao ta không thấy đôi tay cô?"),
        l("The bottom of the panel was cut off", "Phần dưới tấm gỗ đã bị cắt bỏ"), l("Leonardo never painted hands", "Leonardo không bao giờ vẽ tay"),
        l("They were painted over in the 1900s", "Bị vẽ đè lên vào thế kỷ 20"), l("She was hiding them on purpose", "Cô cố tình giấu tay"),
        l("Historians believe a strip with her hands was removed, possibly after damage.", "Các nhà sử học tin rằng một dải gỗ có vẽ đôi tay đã bị cắt đi, có thể do hư hỏng.")),
    ],
  },
  // {
  //   id: "birth-of-venus",
  //   title: l("The Birth of Venus", "Sự ra đời của thần Vệ Nữ"),
  //   artist: "Sandro Botticelli",
  //   year: "c. 1484–1486",
  //   museum: UFFIZI,
  //   aspect: "3:2",
  //   commons: "Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg",
  //   difficulty: "medium",
  //   funFact: l(
  //     "It was one of the first large paintings on canvas in Florence, where wooden panels were the norm.",
  //     "Đây là một trong những bức tranh khổ lớn đầu tiên vẽ trên vải ở Florence, nơi người ta thường vẽ trên gỗ.",
  //   ),
  //   quiz: [
  //     Q("venus-shell", l("What is Venus standing on?", "Thần Vệ Nữ đang đứng trên vật gì?"),
  //       l("A scallop shell", "Một vỏ sò điệp"), l("A rock", "Một tảng đá"), l("A dolphin", "Một con cá heo"), l("A small boat", "Một chiếc thuyền nhỏ"),
  //       l("In the myth, Venus was born from the sea foam and carried ashore on a shell.", "Theo thần thoại, Vệ Nữ sinh ra từ bọt biển và được vỏ sò đưa vào bờ.")),
  //     Q("venus-wind", l("Which wind god blows her towards the shore?", "Thần gió nào thổi nàng vào bờ?"),
  //       l("Zephyrus, the west wind", "Zephyrus, gió tây"), l("Boreas, the north wind", "Boreas, gió bắc"), l("Poseidon", "Poseidon"), l("Hermes", "Hermes"),
  //       l("Zephyrus holds a female figure, often identified as Aura or Chloris.", "Zephyrus ôm một nhân vật nữ, thường được cho là Aura hoặc Chloris.")),
  //     Q("venus-artist", l("Who painted The Birth of Venus?", "Ai vẽ Sự ra đời của thần Vệ Nữ?"),
  //       l("Sandro Botticelli", "Sandro Botticelli"), l("Titian", "Titian"), l("Raphael", "Raphael"), l("Giorgione", "Giorgione"),
  //       l("Botticelli worked in Florence and was close to the Medici circle.", "Botticelli làm việc ở Florence và gần gũi với giới nhà Medici.")),
  //     Q("venus-museum", l("Where can you see it?", "Có thể xem tranh ở đâu?"),
  //       l("The Uffizi, Florence", "Uffizi, Florence"), l("The Louvre, Paris", "Louvre, Paris"), l("The Prado, Madrid", "Prado, Madrid"), l("The Vatican Museums", "Bảo tàng Vatican"),
  //       l("It hangs in the same Botticelli room as Primavera.", "Tranh treo cùng phòng Botticelli với bức Mùa xuân.")),
  //     Q("venus-family", l("Which Florentine family is most associated with Botticelli's patrons?", "Gia tộc Florence nào gắn với những người bảo trợ Botticelli?"),
  //       l("The Medici", "Nhà Medici"), l("The Borgia", "Nhà Borgia"), l("The Sforza", "Nhà Sforza"), l("The Este", "Nhà Este"),
  //       l("Members of the Medici family commissioned several of his mythological paintings.", "Nhiều thành viên nhà Medici đặt vẽ các tranh thần thoại của ông.")),
  //   ],
  // },
  {
    id: "primavera",
    title: l("Primavera", "Mùa xuân (Primavera)"),
    artist: "Sandro Botticelli",
    year: "c. 1480",
    museum: UFFIZI,
    aspect: "3:2",
    commons: "Botticelli-primavera.jpg",
    difficulty: "hard",
    funFact: l(
      "Botanists have identified hundreds of real plant species painted in the meadow.",
      "Các nhà thực vật học đã nhận ra hàng trăm loài cây có thật được vẽ trên đồng cỏ.",
    ),
    quiz: [
      Q("prima-title", l("What does 'Primavera' mean?", "'Primavera' nghĩa là gì?"),
        l("Spring", "Mùa xuân"), l("Summer", "Mùa hè"), l("First love", "Mối tình đầu"), l("Morning", "Buổi sáng"),
        l("The garden of flowers and oranges celebrates the arrival of spring.", "Khu vườn hoa và cam ca ngợi mùa xuân tới.")),
      Q("prima-centre", l("Who stands in the centre of the painting?", "Ai đứng ở chính giữa bức tranh?"),
        l("Venus", "Thần Vệ Nữ"), l("The Virgin Mary", "Đức Mẹ Maria"), l("Flora", "Nữ thần Flora"), l("Athena", "Nữ thần Athena"),
        l("Venus presides over her garden, framed by an arch of leaves.", "Vệ Nữ chủ trì khu vườn của mình, dưới vòm lá.")),
      Q("prima-cupid", l("What is special about Cupid flying above?", "Thần Cupid bay phía trên có gì đặc biệt?"),
        l("He is blindfolded", "Bị bịt mắt"), l("He has no wings", "Không có cánh"), l("He is asleep", "Đang ngủ"), l("He holds a mirror", "Cầm một chiếc gương"),
        l("Love is blind: Cupid aims his arrow at the Three Graces without looking.", "Tình yêu là mù quáng: Cupid nhắm tên vào Ba Nữ thần Duyên dáng mà không nhìn.")),
      Q("prima-graces", l("Who are the three dancing women on the left?", "Ba người phụ nữ đang múa bên trái là ai?"),
        l("The Three Graces", "Ba Nữ thần Duyên dáng"), l("The three Fates", "Ba Nữ thần Số mệnh"), l("Three nuns", "Ba nữ tu"), l("The Muses", "Các nàng thơ Muse"),
        l("The Graces stand for beauty, charm and joy.", "Các nữ thần tượng trưng cho vẻ đẹp, sự duyên dáng và niềm vui.")),
      Q("prima-mercury", l("Who is the figure on the far left, reaching into the clouds?", "Nhân vật ngoài cùng bên trái, vươn tay lên mây là ai?"),
        l("Mercury", "Thần Mercury"), l("Zephyrus", "Thần gió Zephyrus"), l("Mars", "Thần Mars"), l("Apollo", "Thần Apollo"),
        l("Mercury, messenger of the gods, seems to push the clouds away with his staff.", "Mercury, sứ giả của các vị thần, dùng gậy xua mây đi.")),
    ],
  },
  {
    id: "creation-of-adam",
    title: l("The Creation of Adam", "Sự sáng tạo ra Adam"),
    artist: "Michelangelo",
    year: "c. 1508–1512",
    museum: l("Sistine Chapel, Vatican City", "Nhà nguyện Sistine, Vatican"),
    aspect: "2:1",
    commons: "Michelangelo_-_Creation_of_Adam_(cropped).jpg",
    difficulty: "easy",
    funFact: l(
      "Michelangelo painted the whole ceiling standing on scaffolding, not lying on his back as legend says.",
      "Michelangelo vẽ cả trần nhà khi đứng trên giàn giáo, chứ không nằm ngửa như truyền thuyết.",
    ),
    quiz: [
      Q("adam-where", l("Where in the Sistine Chapel is this scene?", "Cảnh này nằm ở đâu trong nhà nguyện Sistine?"),
        l("On the ceiling", "Trên trần"), l("Behind the altar", "Sau bàn thờ"), l("On the floor", "Dưới sàn"), l("On the entrance door", "Trên cửa vào"),
        l("It is one of nine scenes from Genesis along the centre of the ceiling.", "Đây là một trong chín cảnh Sáng thế ký dọc giữa trần nhà.")),
      Q("adam-pope", l("Which pope commissioned the ceiling?", "Giáo hoàng nào đặt vẽ trần nhà?"),
        l("Julius II", "Julius II"), l("Leo X", "Leo X"), l("Sixtus IV", "Sixtus IV"), l("Paul III", "Paul III"),
        l("Julius II hired Michelangelo in 1508.", "Julius II thuê Michelangelo năm 1508.")),
      Q("adam-technique", l("What technique was used?", "Tranh dùng kỹ thuật gì?"),
        l("Fresco — paint on wet plaster", "Bích hoạ — vẽ trên vữa ướt"), l("Oil on canvas", "Sơn dầu trên vải"),
        l("Mosaic tiles", "Ghép đá mosaic"), l("Tapestry", "Thảm dệt"),
        l("Fresco pigments bind with the plaster as it dries, so the artist must work fast.", "Màu bích hoạ kết dính với vữa khi khô, nên hoạ sĩ phải vẽ nhanh.")),
      Q("adam-sculptor", l("What did Michelangelo consider himself first and foremost?", "Michelangelo tự coi mình trước hết là gì?"),
        l("A sculptor", "Nhà điêu khắc"), l("A poet", "Nhà thơ"), l("An architect", "Kiến trúc sư"), l("A priest", "Linh mục"),
        l("He often signed letters 'Michelangelo, sculptor' — he had already carved the David.", "Ông thường ký thư là 'Michelangelo, nhà điêu khắc' — khi ấy ông đã tạc xong tượng David.")),
      Q("adam-brain", l("Some doctors say the shape around God resembles what?", "Một số bác sĩ cho rằng hình khối quanh Chúa giống với gì?"),
        l("A human brain", "Bộ não người"), l("A heart", "Trái tim"), l("A map of Italy", "Bản đồ nước Ý"), l("A shell", "Vỏ sò"),
        l("A 1990 article argued the red cloak and figures form an anatomically accurate brain.", "Một bài báo năm 1990 cho rằng tấm áo choàng đỏ và các nhân vật tạo thành hình bộ não khá chính xác.")),
    ],
  },
  {
    id: "school-of-athens",
    title: l("The School of Athens", "Trường học Athens"),
    artist: "Raphael",
    year: "1509–1511",
    museum: l("Vatican Museums, Vatican City", "Bảo tàng Vatican"),
    aspect: "3:2",
    commons: "\"The_School_of_Athens\"_by_Raffaello_Sanzio_da_Urbino.jpg",
    difficulty: "hard",
    funFact: l(
      "Raphael gave some philosophers the faces of artists of his day — and painted himself among them.",
      "Raphael vẽ một số triết gia mang gương mặt các nghệ sĩ cùng thời — và vẽ cả chính mình trong đó.",
    ),
    quiz: [
      Q("athens-centre", l("Who are the two philosophers in the centre?", "Hai triết gia ở trung tâm là ai?"),
        l("Plato and Aristotle", "Plato và Aristotle"), l("Socrates and Homer", "Socrates và Homer"),
        l("Pythagoras and Euclid", "Pythagoras và Euclid"), l("Cicero and Seneca", "Cicero và Seneca"),
        l("Plato points up to the world of ideas; Aristotle holds his hand flat towards the earth.", "Plato chỉ tay lên thế giới ý niệm; Aristotle đưa bàn tay úp về phía mặt đất.")),
      Q("athens-plato", l("Plato is thought to have the face of which artist?", "Plato được cho là mang gương mặt của nghệ sĩ nào?"),
        l("Leonardo da Vinci", "Leonardo da Vinci"), l("Michelangelo", "Michelangelo"), l("Titian", "Titian"), l("Botticelli", "Botticelli"),
        l("The long white beard matches known portraits of the elderly Leonardo.", "Bộ râu trắng dài khớp với các chân dung Leonardo lúc về già.")),
      Q("athens-room", l("In which room is the fresco?", "Bức bích hoạ nằm trong phòng nào?"),
        l("The Stanza della Segnatura", "Phòng Stanza della Segnatura"), l("The Sistine Chapel", "Nhà nguyện Sistine"),
        l("St Peter's Basilica", "Vương cung thánh đường Thánh Phêrô"), l("The Louvre", "Bảo tàng Louvre"),
        l("It is one of the 'Raphael Rooms' in the Apostolic Palace.", "Đây là một trong các 'Phòng Raphael' trong Điện Tông toà.")),
      Q("athens-self", l("Where did Raphael paint himself?", "Raphael vẽ chính mình ở đâu?"),
        l("Near the right edge, looking out at us", "Gần mép phải, nhìn ra phía người xem"), l("In the centre", "Ở giữa"),
        l("Lying on the steps", "Nằm trên bậc thang"), l("He did not include himself", "Ông không vẽ mình"),
        l("He wears a dark cap and is one of the few figures who meets the viewer's eye.", "Ông đội mũ tối màu và là một trong số ít nhân vật nhìn thẳng ra người xem.")),
      Q("athens-technique", l("What kind of painting is The School of Athens?", "Trường học Athens thuộc loại tranh gì?"),
        l("A fresco on a wall", "Bích hoạ trên tường"), l("Oil on a wooden panel", "Sơn dầu trên gỗ"), l("Tempera on canvas", "Tempera trên vải"), l("A stained-glass window", "Kính màu"),
        l("Raphael painted it directly on the wall of the papal apartment.", "Raphael vẽ trực tiếp lên tường căn phòng của giáo hoàng.")),
    ],
  },
  {
    id: "sistine-madonna",
    title: l("Sistine Madonna", "Đức Mẹ Sistine"),
    artist: "Raphael",
    year: "1512",
    museum: l("Gemäldegalerie Alte Meister, Dresden", "Phòng tranh Bậc thầy Cổ điển, Dresden"),
    aspect: "3:4",
    commons: "Raphael_-_The_Sistine_Madonna_-_Google_Art_Project.jpg",
    difficulty: "medium",
    funFact: l(
      "The two bored-looking cherubs at the bottom have become famous on their own — on stamps, mugs and posters.",
      "Hai thiên thần nhỏ trông chán chường ở phía dưới đã trở nên nổi tiếng riêng — trên tem, cốc và áp phích.",
    ),
    quiz: [
      Q("sistine-cherubs", l("What famous detail is at the bottom of the painting?", "Chi tiết nổi tiếng nào nằm ở cuối bức tranh?"),
        l("Two leaning cherubs", "Hai thiên thần nhỏ tựa cằm"), l("A sleeping dog", "Một chú chó ngủ"), l("A skull", "Một chiếc đầu lâu"), l("The painter's signature", "Chữ ký hoạ sĩ"),
        l("They lean on the frame's edge and gaze upwards.", "Hai thiên thần tựa vào mép khung và ngước nhìn lên.")),
      Q("sistine-city", l("In which city is the painting today?", "Ngày nay tranh ở thành phố nào?"),
        l("Dresden", "Dresden"), l("Rome", "Rome"), l("Piacenza", "Piacenza"), l("Berlin", "Berlin"),
        l("Augustus III of Poland bought it in 1754.", "Vua Augustus III của Ba Lan mua tranh năm 1754.")),
      Q("sistine-church", l("Which church was it painted for?", "Tranh được vẽ cho nhà thờ nào?"),
        l("San Sisto in Piacenza", "San Sisto ở Piacenza"), l("St Peter's in Rome", "Thánh Phêrô ở Rome"),
        l("Florence Cathedral", "Nhà thờ chính toà Florence"), l("St Mark's in Venice", "Thánh Máccô ở Venice"),
        l("The name 'Sistine' comes from San Sisto (Saint Sixtus), not from the Sistine Chapel.", "Tên 'Sistine' bắt nguồn từ San Sisto (Thánh Sixtus), không phải từ nhà nguyện Sistine.")),
      Q("sistine-saints", l("Which saints kneel beside the Madonna?", "Những vị thánh nào quỳ bên Đức Mẹ?"),
        l("Pope Sixtus II and Saint Barbara", "Giáo hoàng Sixtus II và Thánh Barbara"), l("Saint Peter and Saint Paul", "Thánh Phêrô và Thánh Phaolô"),
        l("Saint Francis and Saint Clare", "Thánh Phanxicô và Thánh Clara"), l("Saint George and Saint Michael", "Thánh George và Tổng lãnh Michael"),
        l("Sixtus points out towards us, inviting the viewer into the scene.", "Sixtus chỉ tay ra phía người xem, như mời ta bước vào cảnh.")),
      Q("sistine-support", l("What is it painted on?", "Tranh được vẽ trên chất liệu gì?"),
        l("Canvas", "Vải canvas"), l("A wooden panel", "Tấm gỗ"), l("A plaster wall", "Tường vữa"), l("Copper", "Tấm đồng"),
        l("It is oil on canvas, more than 2.5 metres tall.", "Tranh sơn dầu trên vải, cao hơn 2,5 mét.")),
    ],
  },
  // {
  //   id: "venus-of-urbino",
  //   title: l("Venus of Urbino", "Thần Vệ Nữ xứ Urbino"),
  //   artist: "Titian",
  //   year: "1538",
  //   museum: UFFIZI,
  //   aspect: "4:3",
  //   commons: "Tiziano_-_Venere_di_Urbino_-_Google_Art_Project.jpg",
  //   difficulty: "medium",
  //   funFact: l(
  //     "Édouard Manet's 'Olympia' (1863) deliberately copies this pose.",
  //     "Bức 'Olympia' (1863) của Édouard Manet cố ý mô phỏng tư thế này.",
  //   ),
  //   quiz: [
  //     Q("urbino-dog", l("What animal sleeps at the foot of the bed?", "Con vật nào ngủ ở cuối giường?"),
  //       l("A small dog", "Một chú chó nhỏ"), l("A cat", "Một con mèo"), l("A rabbit", "Một con thỏ"), l("A parrot", "Một con vẹt"),
  //       l("The little dog is often read as a symbol of fidelity.", "Chú chó nhỏ thường được hiểu là biểu tượng của lòng chung thuỷ.")),
  //     Q("urbino-artist", l("Who painted the Venus of Urbino?", "Ai vẽ Thần Vệ Nữ xứ Urbino?"),
  //       l("Titian", "Titian"), l("Botticelli", "Botticelli"), l("Raphael", "Raphael"), l("Giorgione", "Giorgione"),
  //       l("Titian was the leading painter of Venice in the 16th century.", "Titian là hoạ sĩ hàng đầu Venice thế kỷ 16.")),
  //     Q("urbino-patron", l("Who commissioned the painting?", "Ai đặt vẽ bức tranh?"),
  //       l("Guidobaldo della Rovere, later Duke of Urbino", "Guidobaldo della Rovere, sau là Công tước Urbino"),
  //       l("Pope Paul III", "Giáo hoàng Paul III"), l("King Henry VIII", "Vua Henry VIII"), l("Cosimo de' Medici", "Cosimo de' Medici"),
  //       l("The title comes from the Duke of Urbino who bought it.", "Tên tranh bắt nguồn từ vị Công tước Urbino đã mua nó.")),
  //     Q("urbino-background", l("What are the two women in the background doing?", "Hai người phụ nữ phía sau đang làm gì?"),
  //       l("Looking in a clothes chest", "Lục tìm trong rương quần áo"), l("Playing music", "Chơi nhạc"), l("Cooking", "Nấu ăn"), l("Painting", "Vẽ tranh"),
  //       l("Chests like this (cassoni) were typical wedding furniture.", "Những chiếc rương như vậy (cassone) thường là đồ cưới thời đó.")),
  //     Q("urbino-manet", l("Which later painting borrowed this composition?", "Bức tranh nào sau này mượn bố cục này?"),
  //       l("Manet's Olympia", "Olympia của Manet"), l("Van Gogh's Starry Night", "Đêm đầy sao của Van Gogh"),
  //       l("Vermeer's Girl with a Pearl Earring", "Thiếu nữ đeo hoa tai ngọc trai của Vermeer"), l("Monet's Water Lilies", "Hoa súng của Monet"),
  //       l("Manet replaced the goddess with a modern Parisian woman, causing a scandal.", "Manet thay nữ thần bằng một phụ nữ Paris đương thời, gây nên tai tiếng.")),
  //   ],
  // },
  {
    id: "bacchus-and-ariadne",
    title: l("Bacchus and Ariadne", "Bacchus và Ariadne"),
    artist: "Titian",
    year: "1520–1523",
    museum: NG_LONDON,
    aspect: "1:1",
    commons: "Titian_Bacchus_and_Ariadne.jpg",
    difficulty: "hard",
    funFact: l(
      "The brilliant blue sky is made with ultramarine, a pigment ground from lapis lazuli and worth more than gold.",
      "Bầu trời xanh rực được vẽ bằng màu ultramarine nghiền từ đá lapis lazuli, đắt hơn cả vàng.",
    ),
    quiz: [
      Q("bacchus-patron", l("Who commissioned the painting?", "Ai đặt vẽ bức tranh?"),
        l("Alfonso d'Este, Duke of Ferrara", "Alfonso d'Este, Công tước Ferrara"), l("Pope Leo X", "Giáo hoàng Leo X"),
        l("The Doge of Venice", "Tổng trấn Venice"), l("Emperor Charles V", "Hoàng đế Charles V"),
        l("It decorated the Duke's private study, the 'alabaster room'.", "Tranh trang trí phòng làm việc riêng của Công tước, 'căn phòng thạch cao tuyết hoa'.")),
      Q("bacchus-chariot", l("What animals pull Bacchus's chariot?", "Con vật nào kéo cỗ xe của Bacchus?"),
        l("Big cats (cheetahs)", "Báo săn"), l("Horses", "Ngựa"), l("Lions", "Sư tử"), l("Goats", "Dê"),
        l("Titian may have seen exotic big cats kept in the Duke's menagerie.", "Có thể Titian đã thấy báo săn trong vườn thú riêng của Công tước.")),
      Q("bacchus-stars", l("What are the stars in the top-left corner?", "Những ngôi sao ở góc trên bên trái là gì?"),
        l("Ariadne's crown, turned into a constellation", "Vương miện của Ariadne hoá thành chòm sao"), l("A comet", "Một sao chổi"),
        l("The planet Venus", "Sao Kim"), l("Fireworks", "Pháo hoa"),
        l("Bacchus threw Ariadne's crown into the sky, creating the Corona Borealis.", "Bacchus ném vương miện của Ariadne lên trời, tạo nên chòm sao Bắc Miện.")),
      Q("bacchus-theseus", l("Who had abandoned Ariadne on the island?", "Ai đã bỏ rơi Ariadne trên hòn đảo?"),
        l("Theseus", "Theseus"), l("Hercules", "Hercules"), l("Odysseus", "Odysseus"), l("Jason", "Jason"),
        l("Theseus's ship can be seen sailing away in the distance.", "Có thể thấy con tàu của Theseus đang rời xa ở phía chân trời.")),
      Q("bacchus-blue", l("Which precious pigment makes the sky so blue?", "Chất màu quý nào làm bầu trời xanh như vậy?"),
        l("Ultramarine from lapis lazuli", "Ultramarine từ đá lapis lazuli"), l("Indigo", "Chàm"), l("Cobalt blue", "Xanh coban"), l("Prussian blue", "Xanh Phổ"),
        l("Ultramarine came from mines in Afghanistan, 'beyond the sea' — ultra-marine.", "Ultramarine đến từ các mỏ ở Afghanistan, 'bên kia biển' — ultra-marine.")),
    ],
  },
  {
    id: "the-tempest",
    title: l("The Tempest", "Cơn giông"),
    artist: "Giorgione",
    year: "c. 1506–1508",
    museum: l("Gallerie dell'Accademia, Venice", "Phòng tranh Accademia, Venice"),
    aspect: "4:5",
    commons: "Giorgione_019.jpg",
    difficulty: "medium",
    funFact: l(
      "X-rays show that Giorgione first painted a bathing woman where the standing man is now.",
      "Ảnh chụp X-quang cho thấy Giorgione ban đầu vẽ một phụ nữ đang tắm ở vị trí người đàn ông đứng bây giờ.",
    ),
    quiz: [
      Q("tempest-weather", l("What weather event is in the sky?", "Trên bầu trời có hiện tượng thời tiết gì?"),
        l("A flash of lightning", "Một tia chớp"), l("A rainbow", "Cầu vồng"), l("Snow", "Tuyết"), l("An eclipse", "Nhật thực"),
        l("The lightning bolt over the city gives the painting its name.", "Tia chớp phía trên thành phố đặt tên cho bức tranh.")),
      Q("tempest-artist", l("Who painted The Tempest?", "Ai vẽ Cơn giông?"),
        l("Giorgione", "Giorgione"), l("Titian", "Titian"), l("Bellini", "Bellini"), l("Tintoretto", "Tintoretto"),
        l("Giorgione died young, around 1510, and very few works are securely his.", "Giorgione mất trẻ, khoảng năm 1510, và rất ít tác phẩm chắc chắn là của ông.")),
      Q("tempest-woman", l("What is the woman on the right doing?", "Người phụ nữ bên phải đang làm gì?"),
        l("Nursing a baby", "Cho em bé bú"), l("Reading", "Đọc sách"), l("Fishing", "Câu cá"), l("Sleeping", "Ngủ"),
        l("She sits almost unclothed in the open landscape, looking out at us.", "Bà ngồi gần như không mặc gì giữa cảnh thiên nhiên, nhìn ra phía người xem.")),
      Q("tempest-xray", l("What did X-rays reveal under the standing man?", "Ảnh X-quang phát hiện gì bên dưới người đàn ông đứng?"),
        l("A woman bathing", "Một phụ nữ đang tắm"), l("A horse", "Một con ngựa"), l("A second city", "Một thành phố khác"), l("Nothing", "Không có gì"),
        l("Giorgione changed his mind while painting — the meaning is still debated.", "Giorgione đổi ý khi đang vẽ — ý nghĩa bức tranh đến nay vẫn còn tranh cãi.")),
      Q("tempest-city", l("In which city is the painting kept?", "Tranh được lưu giữ ở thành phố nào?"),
        l("Venice", "Venice"), l("Florence", "Florence"), l("Milan", "Milan"), l("Naples", "Naples"),
        l("It hangs in the Gallerie dell'Accademia.", "Tranh treo tại Phòng tranh Accademia.")),
    ],
  },
  {
    id: "baptism-of-christ",
    title: l("The Baptism of Christ", "Lễ rửa tội của Chúa Kitô"),
    artist: "Piero della Francesca",
    year: "c. 1450",
    museum: NG_LONDON,
    aspect: "3:4",
    commons: "Piero_della_Francesca_-_Battesimo_di_Cristo_(National_Gallery,_London).jpg",
    difficulty: "medium",
    funFact: l(
      "Piero was also a mathematician who wrote treatises on perspective and geometry.",
      "Piero còn là nhà toán học, từng viết sách về phối cảnh và hình học.",
    ),
    quiz: [
      Q("baptism-john", l("Who is baptising Christ?", "Ai đang làm lễ rửa tội cho Chúa?"),
        l("John the Baptist", "Thánh Gioan Tẩy Giả"), l("Saint Peter", "Thánh Phêrô"), l("Moses", "Môsê"), l("An angel", "Một thiên thần"),
        l("John pours water from a small bowl over Christ's head.", "Thánh Gioan dội nước từ chiếc bát nhỏ lên đầu Chúa.")),
      Q("baptism-dove", l("What hovers above Christ's head?", "Vật gì lơ lửng trên đầu Chúa?"),
        l("A white dove", "Một con chim bồ câu trắng"), l("A crown", "Một vương miện"), l("A star", "Một ngôi sao"), l("A cloud", "Một đám mây"),
        l("The dove represents the Holy Spirit; it is foreshortened to look like a cloud.", "Chim bồ câu tượng trưng cho Chúa Thánh Thần, được vẽ thu ngắn giống như một đám mây.")),
      Q("baptism-angels", l("How many angels watch from the left?", "Có bao nhiêu thiên thần đứng xem bên trái?"),
        l("Three", "Ba"), l("One", "Một"), l("Two", "Hai"), l("Seven", "Bảy"),
        l("The three angels stand beside a tree, calm and statue-like.", "Ba thiên thần đứng cạnh một thân cây, điềm tĩnh như tượng.")),
      Q("baptism-town", l("The town in the background is probably Piero's home town. Which one?", "Thị trấn ở hậu cảnh có lẽ là quê của Piero. Đó là đâu?"),
        l("Sansepolcro", "Sansepolcro"), l("Siena", "Siena"), l("Pisa", "Pisa"), l("Assisi", "Assisi"),
        l("The panel was painted for a church in Sansepolcro, Tuscany.", "Tấm tranh được vẽ cho một nhà thờ ở Sansepolcro, vùng Tuscany.")),
      Q("baptism-technique", l("What paint did Piero use?", "Piero dùng loại sơn gì?"),
        l("Egg tempera", "Tempera trứng"), l("Acrylic", "Acrylic"), l("Watercolour", "Màu nước"), l("Pastel", "Phấn tiên"),
        l("Egg tempera dries fast and gives the clear, pale light typical of Piero.", "Tempera trứng khô nhanh, tạo thứ ánh sáng trong trẻo, nhạt màu đặc trưng của Piero.")),
    ],
  },
  {
    id: "arnolfini-portrait",
    title: l("The Arnolfini Portrait", "Chân dung vợ chồng Arnolfini"),
    artist: "Jan van Eyck",
    year: "1434",
    museum: NG_LONDON,
    aspect: "3:4",
    commons: "Van_Eyck_-_Arnolfini_Portrait.jpg",
    difficulty: "medium",
    funFact: l(
      "The tiny convex mirror reflects the whole room, including two figures standing in the doorway.",
      "Chiếc gương cầu lồi nhỏ phản chiếu cả căn phòng, kể cả hai người đứng ở cửa.",
    ),
    quiz: [
      Q("arnolfini-mirror", l("What hangs on the back wall?", "Vật gì treo trên bức tường phía sau?"),
        l("A round convex mirror", "Một chiếc gương cầu lồi"), l("A clock", "Một chiếc đồng hồ"), l("A map", "Một tấm bản đồ"), l("A window", "Một ô cửa sổ"),
        l("The frame is decorated with ten tiny scenes of Christ's Passion.", "Khung gương trang trí mười cảnh nhỏ về cuộc Khổ nạn của Chúa.")),
      Q("arnolfini-signature", l("What does the Latin inscription above the mirror say?", "Dòng chữ Latin phía trên gương viết gì?"),
        l("Jan van Eyck was here, 1434", "Jan van Eyck đã ở đây, 1434"), l("God bless this house", "Chúa ban phước cho ngôi nhà này"),
        l("Love conquers all", "Tình yêu chinh phục tất cả"), l("Made in Bruges", "Làm tại Bruges"),
        l("'Johannes de eyck fuit hic 1434' — almost like graffiti signed by a witness.", "'Johannes de eyck fuit hic 1434' — gần giống một dòng ký tên của nhân chứng.")),
      Q("arnolfini-dog", l("What animal stands at the couple's feet?", "Con vật nào đứng dưới chân đôi vợ chồng?"),
        l("A small dog", "Một chú chó nhỏ"), l("A cat", "Một con mèo"), l("A lamb", "Một con cừu non"), l("A monkey", "Một con khỉ"),
        l("The little terrier-like dog may symbolise loyalty — or simply be the family pet.", "Chú chó nhỏ có thể tượng trưng cho lòng trung thành — hoặc đơn giản là thú cưng của gia đình.")),
      Q("arnolfini-candle", l("How many candles are lit in the chandelier?", "Có bao nhiêu ngọn nến được thắp trên chùm đèn?"),
        l("One", "Một"), l("None", "Không có"), l("Three", "Ba"), l("Six", "Sáu"),
        l("A single candle burns in daylight, a detail with many proposed meanings.", "Một ngọn nến duy nhất cháy giữa ban ngày — chi tiết có nhiều cách giải thích.")),
      Q("arnolfini-city", l("In which city did van Eyck live and work?", "Van Eyck sống và làm việc ở thành phố nào?"),
        l("Bruges", "Bruges"), l("Amsterdam", "Amsterdam"), l("Paris", "Paris"), l("Cologne", "Cologne"),
        l("Giovanni Arnolfini was an Italian merchant living in Bruges.", "Giovanni Arnolfini là thương nhân người Ý sống ở Bruges.")),
    ],
  },
  // {
  //   id: "garden-of-earthly-delights",
  //   title: l("The Garden of Earthly Delights", "Khu vườn khoái lạc trần gian"),
  //   artist: "Hieronymus Bosch",
  //   year: "c. 1490–1510",
  //   museum: l("Museo del Prado, Madrid", "Bảo tàng Prado, Madrid"),
  //   aspect: "16:9",
  //   commons: "The_Garden_of_earthly_delights.jpg",
  //   difficulty: "expert",
  //   funFact: l(
  //     "In the hell panel, a musical score is painted on a sinner's bottom — musicians have performed it.",
  //     "Ở tấm tranh địa ngục, một bản nhạc được vẽ trên mông một tội nhân — các nhạc công đã từng biểu diễn nó.",
  //   ),
  //   quiz: [
  //     Q("garden-format", l("What format is the painting?", "Bức tranh có hình thức gì?"),
  //       l("A triptych — three hinged panels", "Bộ ba tấm (triptych) có bản lề"), l("A single canvas", "Một tấm vải duy nhất"),
  //       l("A ceiling fresco", "Bích hoạ trần"), l("A tapestry", "Thảm dệt"),
  //       l("The two side panels fold shut over the central one.", "Hai tấm bên gập lại che tấm giữa.")),
  //     Q("garden-left", l("What does the left panel show?", "Tấm bên trái vẽ gì?"),
  //       l("The Garden of Eden", "Vườn Địa Đàng"), l("Hell", "Địa ngục"), l("A battle", "Một trận chiến"), l("A city market", "Một khu chợ"),
  //       l("God presents Eve to Adam among strange animals.", "Chúa giới thiệu Eva với Adam giữa những con vật kỳ lạ.")),
  //     Q("garden-right", l("What does the right panel show?", "Tấm bên phải vẽ gì?"),
  //       l("Hell", "Địa ngục"), l("Heaven", "Thiên đường"), l("The Last Supper", "Bữa tiệc ly"), l("A winter landscape", "Cảnh mùa đông"),
  //       l("A dark, burning hellscape full of giant musical instruments used as torture devices.", "Một địa ngục tối tăm rực lửa, đầy nhạc cụ khổng lồ dùng làm dụng cụ tra tấn.")),
  //     Q("garden-closed", l("What appears on the outside when the wings are closed?", "Khi gập hai cánh lại, mặt ngoài có hình gì?"),
  //       l("The world inside a glass sphere", "Thế giới trong một quả cầu thuỷ tinh"), l("Bosch's portrait", "Chân dung Bosch"),
  //       l("A blank wooden board", "Gỗ trơn"), l("A map of Spain", "Bản đồ Tây Ban Nha"),
  //       l("Painted in shades of grey, it shows the Earth during Creation.", "Vẽ bằng các sắc xám, cảnh này cho thấy Trái Đất lúc được tạo dựng.")),
  //     Q("garden-city", l("In which city is it displayed?", "Tranh được trưng bày ở thành phố nào?"),
  //       l("Madrid", "Madrid"), l("Antwerp", "Antwerp"), l("Amsterdam", "Amsterdam"), l("Brussels", "Brussels"),
  //       l("King Philip II of Spain acquired it; it is now in the Prado.", "Vua Philip II của Tây Ban Nha mua lại; nay tranh ở bảo tàng Prado.")),
  //   ],
  // },
  {
    id: "hunters-in-the-snow",
    title: l("Hunters in the Snow", "Những người thợ săn trong tuyết"),
    artist: "Pieter Bruegel the Elder",
    year: "1565",
    museum: KHM,
    aspect: "4:3",
    commons: "Pieter_Bruegel_the_Elder_-_Hunters_in_the_Snow_(Winter)_-_Google_Art_Project.jpg",
    difficulty: "hard",
    funFact: l(
      "It belongs to a series about the times of the year; five of the six paintings survive.",
      "Tranh thuộc loạt tranh về các thời điểm trong năm; năm trong sáu bức còn tồn tại.",
    ),
    quiz: [
      Q("hunters-catch", l("What have the tired hunters caught?", "Những người thợ săn mệt mỏi bắt được gì?"),
        l("Only a single fox", "Chỉ một con cáo"), l("A deer", "Một con hươu"), l("A wild boar", "Một con lợn rừng"), l("Many rabbits", "Nhiều con thỏ"),
        l("The poor catch hints at a hard winter.", "Chiến lợi phẩm ít ỏi gợi về một mùa đông khắc nghiệt.")),
      Q("hunters-valley", l("What are the people in the valley doing?", "Mọi người dưới thung lũng đang làm gì?"),
        l("Skating on frozen ponds", "Trượt băng trên ao đóng băng"), l("Harvesting wheat", "Gặt lúa mì"), l("Swimming", "Bơi lội"), l("Fighting a battle", "Đánh trận"),
        l("Tiny figures skate, play and pull sledges on the ice.", "Những hình người tí hon trượt băng, vui chơi và kéo xe trượt trên băng.")),
      Q("hunters-series", l("The painting is part of a series about what?", "Bức tranh thuộc loạt tranh về chủ đề gì?"),
        l("The times of the year", "Các thời điểm trong năm"), l("The seven deadly sins", "Bảy mối tội đầu"),
        l("The life of Christ", "Cuộc đời Chúa Kitô"), l("Famous battles", "Các trận chiến nổi tiếng"),
        l("A wealthy Antwerp merchant commissioned the cycle for his house.", "Một thương nhân giàu có ở Antwerp đặt vẽ loạt tranh cho ngôi nhà của mình.")),
      Q("hunters-artist", l("Who painted Hunters in the Snow?", "Ai vẽ Những người thợ săn trong tuyết?"),
        l("Pieter Bruegel the Elder", "Pieter Bruegel Cha"), l("Albrecht Dürer", "Albrecht Dürer"), l("Hieronymus Bosch", "Hieronymus Bosch"), l("Jan van Eyck", "Jan van Eyck"),
        l("Bruegel is famous for lively scenes of peasant life.", "Bruegel nổi tiếng với những cảnh sinh hoạt nông dân sống động.")),
      Q("hunters-city", l("Which city's museum holds the painting?", "Bảo tàng ở thành phố nào giữ bức tranh?"),
        l("Vienna", "Vienna"), l("Antwerp", "Antwerp"), l("Brussels", "Brussels"), l("Prague", "Prague"),
        l("The Kunsthistorisches Museum has the world's largest collection of Bruegel paintings.", "Bảo tàng Lịch sử Nghệ thuật Vienna có bộ sưu tập tranh Bruegel lớn nhất thế giới.")),
    ],
  },
  {
    id: "tower-of-babel",
    title: l("The Tower of Babel", "Tháp Babel"),
    artist: "Pieter Bruegel the Elder",
    year: "1563",
    museum: KHM,
    aspect: "4:3",
    commons: "Pieter_Bruegel_the_Elder_-_The_Tower_of_Babel_(Vienna)_-_Google_Art_Project_-_edited.jpg",
    difficulty: "hard",
    funFact: l(
      "Bruegel painted at least two Towers of Babel; the smaller one is in Rotterdam.",
      "Bruegel vẽ ít nhất hai bức Tháp Babel; bức nhỏ hơn hiện ở Rotterdam.",
    ),
    quiz: [
      Q("babel-story", l("Where does the story of the Tower of Babel come from?", "Câu chuyện Tháp Babel xuất phát từ đâu?"),
        l("The Book of Genesis", "Sách Sáng thế ký"), l("Greek mythology", "Thần thoại Hy Lạp"), l("Norse sagas", "Truyền thuyết Bắc Âu"), l("The Odyssey", "Sử thi Odyssey"),
        l("God confused the builders' language so they could no longer understand each other.", "Chúa làm rối loạn ngôn ngữ của những người xây tháp để họ không còn hiểu nhau.")),
      Q("babel-colosseum", l("Which real building inspired the tower's arches?", "Công trình có thật nào gợi cảm hứng cho các vòm tháp?"),
        l("The Colosseum in Rome", "Đấu trường Colosseum ở Rome"), l("Notre-Dame in Paris", "Nhà thờ Đức Bà Paris"),
        l("The Leaning Tower of Pisa", "Tháp nghiêng Pisa"), l("The Great Pyramid", "Kim tự tháp Giza"),
        l("Bruegel had visited Rome around 1553.", "Bruegel từng đến Rome khoảng năm 1553.")),
      Q("babel-king", l("Which king inspects the work in the foreground?", "Vị vua nào đang thị sát công trình ở tiền cảnh?"),
        l("Nimrod", "Nimrod"), l("Solomon", "Solomon"), l("David", "David"), l("Charlemagne", "Charlemagne"),
        l("Workers kneel before Nimrod, the legendary builder of the tower.", "Thợ xây quỳ trước Nimrod, vị vua huyền thoại cho xây tháp.")),
      Q("babel-rotterdam", l("Where is Bruegel's second, smaller version?", "Phiên bản nhỏ hơn thứ hai của Bruegel ở đâu?"),
        l("Rotterdam", "Rotterdam"), l("London", "London"), l("New York", "New York"), l("Madrid", "Madrid"),
        l("It is in the Museum Boijmans Van Beuningen.", "Tranh ở Bảo tàng Boijmans Van Beuningen.")),
      Q("babel-unfinished", l("What state is the tower in?", "Toà tháp đang ở tình trạng nào?"),
        l("Still under construction", "Vẫn đang xây dở"), l("Completely finished", "Đã hoàn thành"), l("Burnt down", "Bị thiêu rụi"), l("Flooded", "Bị ngập lụt"),
        l("Cranes, scaffolding and ships unloading stone show the work in progress.", "Cần cẩu, giàn giáo và thuyền dỡ đá cho thấy công trình đang thi công.")),
    ],
  },
  {
    id: "the-ambassadors",
    title: l("The Ambassadors", "Hai sứ thần"),
    artist: "Hans Holbein the Younger",
    year: "1533",
    museum: NG_LONDON,
    aspect: "1:1",
    commons: "Hans_Holbein_the_Younger_-_The_Ambassadors_-_Google_Art_Project.jpg",
    difficulty: "hard",
    funFact: l(
      "Stand close to the right side of the painting and the smear on the floor becomes a skull.",
      "Đứng sát mép phải bức tranh, vệt méo trên sàn sẽ hiện thành chiếc đầu lâu.",
    ),
    quiz: [
      Q("ambassadors-skull", l("What is the strange distorted shape at the bottom?", "Hình méo kỳ lạ ở phía dưới là gì?"),
        l("A skull", "Một chiếc đầu lâu"), l("A lute", "Một cây đàn luýt"), l("A carpet", "Một tấm thảm"), l("A globe", "Một quả địa cầu"),
        l("It is painted in anamorphic perspective and only looks right from the side.", "Nó được vẽ theo phép phối cảnh méo (anamorphosis), chỉ nhìn đúng khi đứng lệch sang một bên.")),
      Q("ambassadors-artist", l("Who painted The Ambassadors?", "Ai vẽ Hai sứ thần?"),
        l("Hans Holbein the Younger", "Hans Holbein Con"), l("Albrecht Dürer", "Albrecht Dürer"), l("Jan van Eyck", "Jan van Eyck"), l("Titian", "Titian"),
        l("Holbein was born in Augsburg and worked in Basel and London.", "Holbein sinh ở Augsburg, làm việc tại Basel và London.")),
      Q("ambassadors-king", l("Holbein became court painter to which king?", "Holbein trở thành hoạ sĩ cung đình của vị vua nào?"),
        l("Henry VIII of England", "Henry VIII của Anh"), l("Francis I of France", "Francis I của Pháp"), l("Philip II of Spain", "Philip II của Tây Ban Nha"), l("Charles V", "Charles V"),
        l("His portraits of Henry VIII shaped how we picture the king today.", "Chân dung Henry VIII của ông định hình hình ảnh nhà vua mà ta biết ngày nay.")),
      Q("ambassadors-lute", l("Which musical instrument on the shelf has a broken string?", "Nhạc cụ nào trên kệ bị đứt dây?"),
        l("The lute", "Cây đàn luýt"), l("The violin", "Cây vĩ cầm"), l("The harp", "Cây đàn hạc"), l("The flute", "Cây sáo"),
        l("The broken string is often read as a sign of discord in Europe at the time.", "Sợi dây đứt thường được hiểu là dấu hiệu bất hoà ở châu Âu thời bấy giờ.")),
      Q("ambassadors-who", l("Which country did the two men represent?", "Hai người đàn ông đại diện cho quốc gia nào?"),
        l("France", "Pháp"), l("Spain", "Tây Ban Nha"), l("Venice", "Venice"), l("The Holy Roman Empire", "Đế quốc La Mã Thần thánh"),
        l("Jean de Dinteville was the French ambassador in London; Georges de Selve was a bishop and diplomat.", "Jean de Dinteville là đại sứ Pháp ở London; Georges de Selve là giám mục kiêm nhà ngoại giao.")),
    ],
  },
  {
    id: "durer-self-portrait",
    title: l("Self-Portrait (1500)", "Chân dung tự hoạ năm 1500"),
    artist: "Albrecht Dürer",
    year: "1500",
    museum: l("Alte Pinakothek, Munich", "Alte Pinakothek, Munich"),
    aspect: "4:5",
    commons: "Albrecht_Dürer_-_1500_self-portrait_(High_resolution_and_detail).jpg",
    difficulty: "easy",
    funFact: l(
      "Dürer's 'AD' monogram became one of the first artist trademarks — he even sued copyists.",
      "Chữ lồng 'AD' của Dürer là một trong những thương hiệu nghệ sĩ đầu tiên — ông còn kiện cả người sao chép.",
    ),
    quiz: [
      Q("durer-pose", l("What makes this self-portrait so unusual for its time?", "Điều gì khiến bức tự hoạ này khác thường so với thời đó?"),
        l("A frontal, Christ-like pose", "Tư thế nhìn thẳng, giống hình tượng Chúa Kitô"), l("It shows him as an old man", "Vẽ ông khi đã già"),
        l("He is wearing armour", "Ông mặc áo giáp"), l("It is painted on glass", "Vẽ trên kính"),
        l("Strictly frontal poses were normally reserved for images of Christ.", "Tư thế nhìn thẳng tuyệt đối thường chỉ dành cho hình ảnh Chúa Kitô.")),
      Q("durer-age", l("How old was Dürer when he painted it?", "Dürer bao nhiêu tuổi khi vẽ bức này?"),
        l("28", "28"), l("18", "18"), l("45", "45"), l("60", "60"),
        l("The inscription says he painted himself at the age of 28.", "Dòng chữ ghi rằng ông tự vẽ mình ở tuổi 28.")),
      Q("durer-city", l("What was Dürer's home city?", "Quê hương của Dürer là thành phố nào?"),
        l("Nuremberg", "Nuremberg"), l("Munich", "Munich"), l("Vienna", "Vienna"), l("Venice", "Venice"),
        l("He spent most of his life in Nuremberg, where his house is now a museum.", "Ông sống phần lớn đời ở Nuremberg; ngôi nhà của ông nay là bảo tàng.")),
      Q("durer-prints", l("Besides painting, Dürer was famous for…", "Ngoài hội hoạ, Dürer nổi tiếng với…"),
        l("Woodcuts and engravings", "Tranh khắc gỗ và khắc đồng"), l("Stained glass", "Kính màu"), l("Architecture", "Kiến trúc"), l("Music", "Âm nhạc"),
        l("Prints like 'Melencolia I' and 'Rhinoceros' spread his fame across Europe.", "Những bản in như 'Melencolia I' và 'Con tê giác' làm ông nổi tiếng khắp châu Âu.")),
      Q("durer-museum", l("In which city is the painting today?", "Ngày nay bức tranh ở thành phố nào?"),
        l("Munich", "Munich"), l("Nuremberg", "Nuremberg"), l("Berlin", "Berlin"), l("Paris", "Paris"),
        l("It hangs in the Alte Pinakothek.", "Tranh treo tại Alte Pinakothek.")),
    ],
  },
  {
    id: "baldassare-castiglione",
    title: l("Portrait of Baldassare Castiglione", "Chân dung Baldassare Castiglione"),
    artist: "Raphael",
    year: "c. 1514–1515",
    museum: LOUVRE,
    aspect: "4:5",
    commons: "Baldassare_Castiglione,_by_Raffaello_Sanzio,_from_C2RMF_retouched.jpg",
    difficulty: "easy",
    funFact: l(
      "Rembrandt sketched this portrait when it was auctioned in Amsterdam in 1639.",
      "Rembrandt từng ký hoạ lại bức chân dung này khi nó được bán đấu giá ở Amsterdam năm 1639.",
    ),
    quiz: [
      Q("castiglione-book", l("Castiglione is famous for writing which book?", "Castiglione nổi tiếng với cuốn sách nào?"),
        l("The Book of the Courtier", "Sách về người cận thần (Il Cortegiano)"), l("The Prince", "Quân vương"),
        l("The Divine Comedy", "Thần khúc"), l("Utopia", "Utopia"),
        l("It describes the ideal Renaissance gentleman: graceful, cultured, effortless.", "Cuốn sách mô tả người quý ông lý tưởng thời Phục Hưng: thanh lịch, có học, ung dung.")),
      Q("castiglione-artist", l("Who painted this portrait of his friend?", "Ai đã vẽ chân dung người bạn của mình?"),
        l("Raphael", "Raphael"), l("Titian", "Titian"), l("Michelangelo", "Michelangelo"), l("Leonardo da Vinci", "Leonardo da Vinci"),
        l("Raphael and Castiglione were close friends from the court of Urbino.", "Raphael và Castiglione là bạn thân từ triều đình Urbino.")),
      Q("castiglione-colours", l("Which colours dominate the painting?", "Những màu nào chiếm ưu thế trong tranh?"),
        l("Greys, black and white", "Xám, đen và trắng"), l("Bright red and gold", "Đỏ tươi và vàng kim"),
        l("Green and blue", "Xanh lá và xanh dương"), l("Pink and purple", "Hồng và tím"),
        l("The restrained palette matches the calm dignity praised in his book.", "Bảng màu tiết chế phù hợp với vẻ điềm đạm mà cuốn sách của ông ca ngợi.")),
      Q("castiglione-museum", l("Where is the portrait today?", "Ngày nay bức chân dung ở đâu?"),
        l("The Louvre, Paris", "Louvre, Paris"), l("The Uffizi, Florence", "Uffizi, Florence"),
        l("The Rijksmuseum, Amsterdam", "Rijksmuseum, Amsterdam"), l("The Vatican Museums", "Bảo tàng Vatican"),
        l("It entered the French royal collection under Louis XIV.", "Tranh vào bộ sưu tập hoàng gia Pháp dưới thời Louis XIV.")),
      Q("castiglione-rembrandt", l("Which later Dutch master sketched this portrait?", "Bậc thầy Hà Lan nào sau này ký hoạ lại bức chân dung?"),
        l("Rembrandt", "Rembrandt"), l("Vermeer", "Vermeer"), l("Van Gogh", "Van Gogh"), l("Frans Hals", "Frans Hals"),
        l("Rembrandt borrowed the pose for his own self-portraits.", "Rembrandt mượn tư thế này cho các bức tự hoạ của mình.")),
    ],
  },
];

export function getArtwork(id: string): Artwork | undefined {
  return ARTWORKS.find((a) => a.id === id);
}

export const libraryImage = (id: string) => `/library/${id}.jpg`;
export const libraryThumb = (id: string) => `/library/${id}.thumb.jpg`;
